/* global window, document, localStorage, HTMLTemplateElement */

const printOpenedDetailsAttribute = "data-print-opened";
const printRevealedPanelAttribute = "data-print-revealed";
const printRestoredDisplayAttribute = "data-print-restore-display";
const printTabLabelAttribute = "data-print-tab-label";
const printFootnoteAttribute = "data-print-footnote";
const printOriginalThemeAttribute = "data-print-original-theme";
const printHadStoredThemeAttribute = "data-print-had-stored-theme";
const printableHiddenPanelSelector = [
	".notion-tab-panel[hidden]",
	"#autogenerated-post-comments .tab-pane[hidden]",
].join(",");
const printableHiddenTableRowSelector = ".datatable-wrapper tbody tr[style*='display: none']";
const printFootnoteTargetSelector = [
	".notion-text",
	".callout",
	".toggle",
	"li",
	"blockquote",
	".ntable",
	".notion-image-figure",
].join(",");

function applyTheme(theme: string) {
	if (
		theme === "dark" ||
		(theme === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches)
	) {
		document.documentElement.classList.add("dark");
	} else {
		document.documentElement.classList.remove("dark");
	}

	document.getElementById("themeToggle")?.setAttribute("data-theme", theme);
}

window.addEventListener("beforeprint", function () {
	const storedTheme = localStorage.getItem("theme");
	document.documentElement.setAttribute(printOriginalThemeAttribute, storedTheme || "system");
	document.documentElement.setAttribute(printHadStoredThemeAttribute, String(storedTheme !== null));
	localStorage.setItem("theme", "light");
	applyTheme("light");

	document.querySelectorAll("details:not([open])").forEach(function (detail) {
		detail.setAttribute("open", "");
		detail.setAttribute(printOpenedDetailsAttribute, "true");
	});

	document.querySelectorAll(printableHiddenPanelSelector).forEach(function (panel) {
		panel.removeAttribute("hidden");
		panel.setAttribute(printRevealedPanelAttribute, "true");
	});

	document.querySelectorAll("[data-notion-tab-block]").forEach(function (tabBlock) {
		tabBlock.querySelectorAll(":scope > .notion-tab-panel").forEach(function (panel) {
			const labelledBy = panel.getAttribute("aria-labelledby");
			const tabButton = labelledBy ? document.getElementById(labelledBy) : null;
			const tabLabel = tabButton?.textContent?.trim();

			if (!tabLabel || panel.previousElementSibling?.hasAttribute(printTabLabelAttribute)) {
				return;
			}

			const printLabel = document.createElement("div");
			printLabel.className = "notion-tab-print-label";
			printLabel.setAttribute(printTabLabelAttribute, "true");
			printLabel.textContent = tabLabel;
			panel.before(printLabel);
		});
	});

	document.querySelectorAll<HTMLElement>(printableHiddenTableRowSelector).forEach(function (row) {
		row.setAttribute(printRestoredDisplayAttribute, row.style.display);
		row.style.display = "";
	});

	const footnoteInsertionTargets = new Map();
	document.querySelectorAll("[data-margin-note]").forEach(function (marker) {
		if (marker.closest(".footnote-margin-note")) {
			return;
		}

		const noteId = marker.getAttribute("data-margin-note");
		const template = noteId ? document.getElementById(`template-margin-${noteId}`) : null;
		const targetBlock = marker.closest(printFootnoteTargetSelector);

		if (!(template instanceof HTMLTemplateElement) || !targetBlock) {
			return;
		}

		const printFootnote = document.createElement("aside");
		printFootnote.className = "print-footnote";
		printFootnote.setAttribute(printFootnoteAttribute, "true");
		printFootnote.appendChild(template.content.cloneNode(true));

		const insertionTarget = footnoteInsertionTargets.get(targetBlock) || targetBlock;
		insertionTarget.after(printFootnote);
		footnoteInsertionTargets.set(targetBlock, printFootnote);
	});
});

window.addEventListener("afterprint", function () {
	const originalTheme =
		document.documentElement.getAttribute(printOriginalThemeAttribute) || "system";
	const hadStoredTheme =
		document.documentElement.getAttribute(printHadStoredThemeAttribute) === "true";

	if (hadStoredTheme) {
		localStorage.setItem("theme", originalTheme);
	} else {
		localStorage.removeItem("theme");
	}

	applyTheme(originalTheme);
	document.documentElement.removeAttribute(printOriginalThemeAttribute);
	document.documentElement.removeAttribute(printHadStoredThemeAttribute);

	document.querySelectorAll(`details[${printOpenedDetailsAttribute}]`).forEach(function (detail) {
		detail.removeAttribute("open");
		detail.removeAttribute(printOpenedDetailsAttribute);
	});

	document.querySelectorAll(`[${printRevealedPanelAttribute}]`).forEach(function (panel) {
		panel.setAttribute("hidden", "");
		panel.removeAttribute(printRevealedPanelAttribute);
	});

	document
		.querySelectorAll<HTMLElement>(`[${printRestoredDisplayAttribute}]`)
		.forEach(function (row) {
			row.style.display = row.getAttribute(printRestoredDisplayAttribute) || "";
			row.removeAttribute(printRestoredDisplayAttribute);
		});

	document.querySelectorAll(`[${printTabLabelAttribute}]`).forEach(function (label) {
		label.remove();
	});

	document.querySelectorAll(`[${printFootnoteAttribute}]`).forEach(function (footnote) {
		footnote.remove();
	});
});
